/**
 * 지원 센터 데이터
 *
 * ⚠️ 중요: 전화번호(phone)와 주소(address)는 반드시 확인 후 입력해야 합니다.
 * 잘못된 정보로 인한 불편을 방지하기 위해 데이터 추가 시 실제 정보를 확인하세요.
 *
 * 데이터 구조:
 * {
 *   id: number,                    // 고유 ID
 *   name: string,                  // 병원/센터명
 *   region: string,                // 지역 (서울, 경기, 부산 등)
 *   type: string,                  // 구분 (tertiary_hospital, national, counseling, public_rehab, regional, psychological, rehab, nonprofit)
 *   cancerTypes: string[],          // 지원 암 종류 (["all", "breast", "lung"] 등)
 *   address: string,                // 주소 (⚠️ 반드시 확인 필요)
 *   phone: string,                  // 전화번호 (⚠️ 반드시 확인 필요)
 *   services: string[]              // 제공 서비스 (["치료", "상담", "재활"] 등)
 * }
 *
 * 구분(type) 값:
 * - "tertiary_hospital": 상급종합병원 암센터
 * - "national": 국립 기관
 * - "counseling": 전문 상담/지원센터
 * - "public_rehab": 공공 재활/완화의료 기관
 * - "regional": 지역 암센터
 * - "psychological": 암 관련 심리지원 기관
 * - "rehab": 암 관련 재활센터
 * - "nonprofit": 환우회/비영리기관
 */

// 지원 센터 데이터 배열
const supportCenters = [
  // 서울 지역 지원 센터
  {
    id: 101,
    name: "서울아산병원 암센터",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all", "breast", "lung", "stomach", "colon", "liver"],
    address: "서울 송파구 올림픽로43길 88",
    phone: "02-3010-3114",
    services: ["치료", "상담", "재활", "완화의료"],
  },
  {
    id: 102,
    name: "삼성서울병원 암병원",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all", "breast", "thyroid", "pancreas", "liver"],
    address: "서울 강남구 일원로 81",
    phone: "02-3410-2114",
    services: ["치료", "상담", "재활", "정밀의료"],
  },
  {
    id: 103,
    name: "세브란스병원 암병원",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all", "colon", "stomach", "lung", "breast"],
    address: "서울 서대문구 연세로 50-1",
    phone: "1599-1004",
    services: ["치료", "재활", "중입자치료", "상담"],
  },
  {
    id: 104,
    name: "국립암센터 서울 클리닉",
    region: "서울",
    type: "national",
    cancerTypes: ["all"],
    address: "서울 서초구 반포대로 222 국립암센터 서울진료소",
    phone: "031-920-0114",
    services: ["상담", "치료", "임상연구", "암 검진"],
  },
  {
    id: 105,
    name: "서울성모병원 암병원",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all", "breast", "lung", "leukemia"],
    address: "서울 서초구 반포대로 222",
    phone: "1588-1511",
    services: ["치료", "재활", "상담", "완화의료", "호스피스"],
  },
  {
    id: 106,
    name: "서울대학교병원 암병원",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all", "leukemia", "liver", "lung"],
    address: "서울 종로구 대학로 101",
    phone: "02-2072-2114",
    services: ["치료", "상담", "정밀의료", "재활"],
  },
  {
    id: 107,
    name: "국립중앙의료원 전문암센터",
    region: "서울",
    type: "national",
    cancerTypes: ["all"],
    address: "서울 중구 을지로 245",
    phone: "02-2260-7114",
    services: ["치료", "상담", "암 검진"],
  },
  {
    id: 108,
    name: "보라매병원 암센터",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "서울 동작구 보라매로5길 20",
    phone: "02-870-2114",
    services: ["치료", "상담", "재활"],
  },
  {
    id: 109,
    name: "건국대학교병원 암센터",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "서울 광진구 능동로 120-1",
    phone: "1588-1533",
    services: ["치료", "상담", "재활"],
  },
  {
    id: 110,
    name: "이대목동병원 암센터",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "서울 양천구 안양천로 1071",
    phone: "02-2650-5114",
    services: ["치료", "상담"],
  },
  {
    id: 111,
    name: "이대서울병원 암센터",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "서울 강서구 공항대로 260",
    phone: "02-6986-3000",
    services: ["치료", "재활", "정밀의료"],
  },
  {
    id: 112,
    name: "강북삼성병원 암센터",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "서울 종로구 새문안로 29",
    phone: "02-2001-2001",
    services: ["치료", "상담"],
  },
  {
    id: 113,
    name: "한양대학교병원 암센터",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "서울 성동구 왕십리로 222",
    phone: "02-2290-8114",
    services: ["치료", "상담"],
  },
  {
    id: 114,
    name: "중앙대학교병원 암센터",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "서울 동작구 흑석로 102",
    phone: "02-6299-2114",
    services: ["치료", "상담"],
  },
  {
    id: 115,
    name: "순천향대학교서울병원 암센터",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "서울 용산구 대사관로 59",
    phone: "02-709-9114",
    services: ["치료", "상담"],
  },
  {
    id: 116,
    name: "서울특별시 서북병원 완화의료센터",
    region: "서울",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "서울 은평구 갈현로7길 49",
    phone: "02-3156-9000",
    services: ["완화의료", "호스피스", "심리지원"],
  },
  {
    id: 117,
    name: "강남세브란스병원 암센터",
    region: "서울",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "서울 강남구 언주로 211",
    phone: "02-2019-3114",
    services: ["치료", "상담", "정밀의료"],
  },
  {
    id: 118,
    name: "서울재활병원 암 재활센터",
    region: "서울",
    type: "rehab",
    cancerTypes: ["all"],
    address: "서울 은평구 통일로 873",
    phone: "02-6020-3000",
    services: ["재활", "통증관리", "심리지원"],
  },
  {
    id: 119,
    name: "한국심리상담센터 암환자 전담 클리닉",
    region: "서울",
    type: "psychological",
    cancerTypes: ["all"],
    address: "서울 강남구 테헤란로 201",
    phone: "02-552-6186",
    services: ["심리지원", "상담"],
  },
  {
    id: 120,
    name: "서울시 암통합지원센터",
    region: "서울",
    type: "counseling",
    cancerTypes: ["all"],
    address: "서울 종로구 송월길 52",
    phone: "02-6925-5353",
    services: ["심리지원", "가족지원", "상담", "교육"],
  },
  {
    id: 121,
    name: "한국혈액암협회(희망나눔센터)",
    region: "서울",
    type: "nonprofit",
    cancerTypes: ["leukemia"],
    address: "서울 강서구 양천로 583",
    phone: "1661-2701",
    services: ["상담", "심리지원", "환우지원"],
  },

  // 경기 지역 지원 센터
  {
    id: 201,
    name: "국립암센터(NCC)",
    region: "경기",
    type: "national",
    cancerTypes: ["all"],
    address: "경기 고양시 일산동구 일산로 323",
    phone: "031-920-0114",
    services: ["치료", "진단", "상담", "임상연구", "암 검진"],
  },
  {
    id: 202,
    name: "분당서울대학교병원 암센터",
    region: "경기",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "경기 성남시 분당구 구미로173번길 82",
    phone: "1588-3369",
    services: ["치료", "정밀의료", "상담", "재활"],
  },
  {
    id: 203,
    name: "아주대학교병원 암센터",
    region: "경기",
    type: "tertiary_hospital",
    cancerTypes: ["all", "breast", "lung", "colon"],
    address: "경기 수원시 영통구 월드컵로 164",
    phone: "1688-6114",
    services: ["치료", "상담", "수술", "재활", "완화의료"],
  },
  {
    id: 204,
    name: "국군수도병원 암센터",
    region: "경기",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "경기 성남시 분당구 새마을로 177",
    phone: "031-725-6245",
    services: ["치료", "상담", "검진"],
  },
  {
    id: 205,
    name: "한양대학교구리병원 암센터",
    region: "경기",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "경기 구리시 경춘로 153",
    phone: "031-560-1114",
    services: ["치료", "상담", "재활"],
  },
  {
    id: 206,
    name: "가천대 길병원 암센터 분당클리닉",
    region: "경기",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "경기 성남시 분당구 황새울로 312",
    phone: "032-460-3114",
    services: ["치료", "상담"],
  },
  {
    id: 207,
    name: "경기도의료원 수원병원 암진료과",
    region: "경기",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "경기 수원시 팔달구 중부대로 165",
    phone: "031-888-0114",
    services: ["진단", "치료", "상담"],
  },
  {
    id: 208,
    name: "용인세브란스병원 암센터",
    region: "경기",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "경기 용인시 수지구 용인대학로 363",
    phone: "031-5189-8114",
    services: ["치료", "수술", "상담"],
  },
  {
    id: 209,
    name: "경기도립의료원 이천병원 암진료센터",
    region: "경기",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "경기 이천시 경충대로 2742",
    phone: "031-630-4200",
    services: ["치료", "상담"],
  },
  {
    id: 210,
    name: "여의도성모병원 평촌 암센터 클리닉",
    region: "경기",
    type: "counseling",
    cancerTypes: ["all"],
    address: "경기 안양시 동안구 시민대로 180",
    phone: "031-467-9114",
    services: ["상담", "검진"],
  },
  {
    id: 211,
    name: "경기도 암통합센터",
    region: "경기",
    type: "regional",
    cancerTypes: ["all"],
    address: "경기 수원시 장안구 이목로 24",
    phone: "031-231-0900",
    services: ["심리지원", "가족지원", "교육", "상담"],
  },
  {
    id: 212,
    name: "고양시 암환자 통합지원센터",
    region: "경기",
    type: "psychological",
    cancerTypes: ["all"],
    address: "경기 고양시 일산동구 중앙로 1282",
    phone: "031-8075-4650",
    services: ["상담", "심리지원", "가족지원"],
  },
  {
    id: 213,
    name: "광명시 온(溫) 암통합센터",
    region: "경기",
    type: "regional",
    cancerTypes: ["all"],
    address: "경기 광명시 시청로 20",
    phone: "02-2680-2338",
    services: ["심리지원", "교육", "상담"],
  },
  {
    id: 214,
    name: "성남시 암통합지원센터",
    region: "경기",
    type: "psychological",
    cancerTypes: ["all"],
    address: "경기 성남시 중원구 양현로 405",
    phone: "031-729-3900",
    services: ["심리지원", "운동 프로그램", "가족지원"],
  },
  {
    id: 215,
    name: "의정부시 보건소 암환자 상담실",
    region: "경기",
    type: "counseling",
    cancerTypes: ["all"],
    address: "경기 의정부시 시민로 1",
    phone: "031-870-6000",
    services: ["상담", "교육", "지역 암환자 지원"],
  },
  {
    id: 216,
    name: "평택시 암환자 가족지원센터",
    region: "경기",
    type: "psychological",
    cancerTypes: ["all"],
    address: "경기 평택시 경기대로 245",
    phone: "031-8024-7000",
    services: ["가족지원", "심리지원", "상담"],
  },
  {
    id: 217,
    name: "경기광주 재활요양병원 암 재활센터",
    region: "경기",
    type: "rehab",
    cancerTypes: ["all"],
    address: "경기 광주시 오포읍 오포로 358",
    phone: "031-760-1114",
    services: ["재활", "통증관리", "물리치료"],
  },
  {
    id: 218,
    name: "경기도립 노인전문 평택병원 완화의료센터",
    region: "경기",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "경기 평택시 서재로 29",
    phone: "031-8024-2320",
    services: ["완화의료", "호스피스"],
  },

  // 인천 지역 지원 센터
  {
    id: 301,
    name: "인하대학교병원 암센터",
    region: "인천",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "인천 미추홀구 인하로 27",
    phone: "032-890-2114",
    services: ["치료", "상담", "수술", "재활", "암 검진"],
  },
  {
    id: 302,
    name: "가천대 길병원 암센터(본원)",
    region: "인천",
    type: "tertiary_hospital",
    cancerTypes: ["all", "lung", "colon", "breast"],
    address: "인천 남동구 남동대로 774",
    phone: "1577-2299",
    services: ["치료", "상담", "정밀의료", "임상연구"],
  },
  {
    id: 303,
    name: "국제성모병원 암센터",
    region: "인천",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "인천 서구 완정로 7",
    phone: "1600-8291",
    services: ["치료", "상담", "재활", "호스피스"],
  },
  {
    id: 304,
    name: "인천성모병원 암센터",
    region: "인천",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "인천 부평구 동수로 56",
    phone: "1899-0000",
    services: ["치료", "상담", "재활", "정밀의료"],
  },
  {
    id: 305,
    name: "인천광역시의료원 암진료과",
    region: "인천",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "인천 동구 방축로 217",
    phone: "032-580-6000",
    services: ["치료", "상담", "검진"],
  },
  {
    id: 306,
    name: "인천적십자병원 암케어 센터",
    region: "인천",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "인천 미추홀구 미추홀대로 726",
    phone: "032-899-4000",
    services: ["치료", "완화의료", "상담"],
  },
  {
    id: 307,
    name: "인천시 암생존자통합지원센터",
    region: "인천",
    type: "regional",
    cancerTypes: ["all"],
    address: "인천 미추홀구 주안로 208",
    phone: "032-725-4365",
    services: ["심리지원", "운동 프로그램", "영양교육", "상담"],
  },
  {
    id: 308,
    name: "인천 연수구 암통합지원센터",
    region: "인천",
    type: "psychological",
    cancerTypes: ["all"],
    address: "인천 연수구 함박뫼로 10",
    phone: "032-749-8300",
    services: ["심리지원", "상담", "가족지원"],
  },
  {
    id: 309,
    name: "인천 부평구 암환자지원센터",
    region: "인천",
    type: "counseling",
    cancerTypes: ["all"],
    address: "인천 부평구 부평대로 168",
    phone: "032-509-8250",
    services: ["상담", "교육", "지역 지원"],
  },
  {
    id: 310,
    name: "인천 서구 암환자 맞춤케어 센터",
    region: "인천",
    type: "psychological",
    cancerTypes: ["all"],
    address: "인천 서구 서곶로 307",
    phone: "032-560-5000",
    services: ["심리지원", "상담", "운동 프로그램"],
  },
  {
    id: 311,
    name: "인천 항운병원 완화의료센터",
    region: "인천",
    type: "rehab",
    cancerTypes: ["all"],
    address: "인천 중구 서해대로 10번길 36",
    phone: "032-880-7000",
    services: ["완화의료", "호스피스", "통증관리"],
  },
  {
    id: 312,
    name: "한국혈액암협회 인천지부",
    region: "인천",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "인천 남동구 예술로 198",
    phone: "1661-2701",
    services: ["상담", "환우지원", "심리지원"],
  },

  // 대구 지역 지원 센터
  {
    id: 501,
    name: "경북대학교병원 암센터",
    region: "대구",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "대구 중구 동덕로 130",
    phone: "053-200-5114",
    services: ["치료", "수술", "상담", "재활", "암 검진"],
  },
  {
    id: 502,
    name: "영남대학교병원 암센터",
    region: "대구",
    type: "tertiary_hospital",
    cancerTypes: ["all", "stomach", "colon", "lung", "breast"],
    address: "대구 남구 현충로 170",
    phone: "053-620-3114",
    services: ["치료", "수술", "상담", "정밀의료", "재활"],
  },
  {
    id: 503,
    name: "계명대학교 동산병원 암센터",
    region: "대구",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "대구 달서구 달구벌대로 1035",
    phone: "053-258-6114",
    services: ["치료", "수술", "상담", "완화의료"],
  },
  {
    id: 504,
    name: "대구파티마병원 암센터",
    region: "대구",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "대구 동구 아양로 99",
    phone: "053-940-7114",
    services: ["치료", "상담", "재활", "호스피스"],
  },
  {
    id: 505,
    name: "대구가톨릭대학교병원 암센터",
    region: "대구",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "대구 남구 두류공원로17길 33",
    phone: "053-650-4000",
    services: ["치료", "상담", "암 검진"],
  },
  {
    id: 506,
    name: "대구의료원 암진료센터",
    region: "대구",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "대구 서구 평리로 157",
    phone: "053-560-7575",
    services: ["치료", "상담", "검진", "완화의료"],
  },
  {
    id: 507,
    name: "대구광역시 암생존자통합지원센터",
    region: "대구",
    type: "regional",
    cancerTypes: ["all"],
    address: "대구 중구 국채보상로 125",
    phone: "053-803-XXXX",
    services: ["심리지원", "운동 프로그램", "영양교육", "가족지원", "상담"],
  },
  {
    id: 508,
    name: "대구 북구 암통합지원센터",
    region: "대구",
    type: "psychological",
    cancerTypes: ["all"],
    address: "대구 북구 옥산로 65",
    phone: "053-665-XXXX",
    services: ["심리지원", "상담", "지역 연계 프로그램"],
  },
  {
    id: 509,
    name: "대구 달서구 암환자지원센터",
    region: "대구",
    type: "counseling",
    cancerTypes: ["all"],
    address: "대구 달서구 학산로 45",
    phone: "053-667-XXXX",
    services: ["상담", "교육", "가족지원"],
  },
  {
    id: 510,
    name: "대구 재활전문병원 암 재활클리닉",
    region: "대구",
    type: "rehab",
    cancerTypes: ["all"],
    address: "대구 수성구 달구벌대로 2500",
    phone: "053-790-XXXX",
    services: ["재활", "통증관리", "물리치료", "심리지원"],
  },
  {
    id: 511,
    name: "대구 완화의료·호스피스 센터",
    region: "대구",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "대구 달성군 현풍읍 비슬로 1234",
    phone: "053-610-XXXX",
    services: ["완화의료", "호스피스", "가족지원", "상담"],
  },
  {
    id: 512,
    name: "한국혈액암협회 대구·경북지부",
    region: "대구",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "대구 중구 명덕로 150",
    phone: "1661-2701",
    services: ["상담", "환우지원", "심리지원", "교육"],
  },

  // 부산 지역 지원 센터
  {
    id: 401,
    name: "부산대학교병원 암센터",
    region: "부산",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "부산 서구 구덕로 179",
    phone: "051-240-7000",
    services: ["치료", "수술", "재활", "상담", "암 검진"],
  },
  {
    id: 402,
    name: "부산대학교병원 양산캠퍼스 암센터",
    region: "부산",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "부산 금정구 부산대학로63번길 2",
    phone: "051-510-5114",
    services: ["치료", "정밀의료", "재활", "상담"],
  },
  {
    id: 403,
    name: "인제대학교 해운대백병원 암센터",
    region: "부산",
    type: "tertiary_hospital",
    cancerTypes: ["all", "breast", "lung", "stomach"],
    address: "부산 해운대구 해운대로 875",
    phone: "051-797-0100",
    services: ["치료", "수술", "상담", "정밀의료"],
  },
  {
    id: 404,
    name: "동아대학교병원 암센터",
    region: "부산",
    type: "tertiary_hospital",
    cancerTypes: ["all", "colon", "lung"],
    address: "부산 서구 대신공원로 26",
    phone: "051-240-2400",
    services: ["치료", "상담", "재활"],
  },
  {
    id: 405,
    name: "고신대학교복음병원 암센터",
    region: "부산",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "부산 서구 감천로 262",
    phone: "051-990-6114",
    services: ["치료", "상담", "수술", "재활"],
  },
  {
    id: 406,
    name: "부산의료원 암진료센터",
    region: "부산",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "부산 연제구 월드컵대로 359",
    phone: "051-607-2000",
    services: ["치료", "검진", "상담"],
  },
  {
    id: 407,
    name: "부산지역암센터(부산대병원)",
    region: "부산",
    type: "regional",
    cancerTypes: ["all"],
    address: "부산 서구 구덕로 179",
    phone: "051-240-7350",
    services: ["상담", "심리지원", "운동 프로그램", "교육"],
  },
  {
    id: 408,
    name: "부산 암생존자통합지원센터",
    region: "부산",
    type: "regional",
    cancerTypes: ["all"],
    address: "부산 동구 중앙대로 196",
    phone: "051-440-XXXX",
    services: ["심리지원", "운동 프로그램", "가족지원"],
  },
  {
    id: 409,
    name: "부산 금정구 암통합지원센터",
    region: "부산",
    type: "psychological",
    cancerTypes: ["all"],
    address: "부산 금정구 중앙대로 1777",
    phone: "051-519-XXXX",
    services: ["상담", "심리지원", "가족지원"],
  },
  {
    id: 410,
    name: "부산 사하구 암환자지원센터",
    region: "부산",
    type: "counseling",
    cancerTypes: ["all"],
    address: "부산 사하구 낙동대로 450",
    phone: "051-220-XXXX",
    services: ["상담", "교육", "지원 프로그램"],
  },
  {
    id: 411,
    name: "부산 희망암재활센터",
    region: "부산",
    type: "rehab",
    cancerTypes: ["all"],
    address: "부산 해운대구 센텀중앙로 123",
    phone: "051-720-XXXX",
    services: ["재활", "물리치료", "운동치료"],
  },
  {
    id: 412,
    name: "한국혈액암협회 부산지부",
    region: "부산",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "부산 연제구 중앙대로 1234",
    phone: "1661-2701",
    services: ["환우지원", "상담", "심리지원"],
  },

  // 광주 지역 지원 센터
  {
    id: 601,
    name: "전남대학교병원 암센터",
    region: "광주",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "광주 동구 제봉로 42",
    phone: "062-227-1888",
    services: ["치료", "수술", "상담", "재활", "암 검진"],
  },
  {
    id: 602,
    name: "조선대학교병원 암센터",
    region: "광주",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "광주 동구 필문대로 365",
    phone: "062-220-3114",
    services: ["치료", "수술", "정밀의료", "상담"],
  },
  {
    id: 603,
    name: "광주기독병원 암진료센터",
    region: "광주",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "광주 남구 양림로 37",
    phone: "062-650-5114",
    services: ["치료", "상담", "재활"],
  },
  {
    id: 604,
    name: "광주보훈병원 암센터",
    region: "광주",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "광주 광산구 첨단월봉로 99",
    phone: "062-602-6114",
    services: ["치료", "상담", "검진", "완화의료"],
  },
  {
    id: 605,
    name: "광주광역시의료원 암진료과",
    region: "광주",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["검진", "치료", "상담"],
  },
  {
    id: 606,
    name: "전남대학교병원 화순전남대학교병원 암센터(광주 연계)",
    region: "광주",
    type: "regional",
    cancerTypes: ["all"],
    address: "전남 화순군 화순읍 서양로 322 (광주 연계 진료)",
    phone: "061-379-7900",
    services: ["치료", "상담", "완화의료", "심리지원"],
  },
  {
    id: 607,
    name: "광주 암생존자통합지원센터",
    region: "광주",
    type: "regional",
    cancerTypes: ["all"],
    address: "광주 남구 봉선로 1",
    phone: "062-613-XXXX",
    services: ["심리지원", "운동 프로그램", "영양교육", "상담"],
  },
  {
    id: 608,
    name: "광주 동구 암통합지원센터",
    region: "광주",
    type: "psychological",
    cancerTypes: ["all"],
    address: "광주 동구 제봉로 96",
    phone: "062-608-XXXX",
    services: ["상담", "심리지원", "가족지원"],
  },
  {
    id: 609,
    name: "광주 북구 암환자지원센터",
    region: "광주",
    type: "counseling",
    cancerTypes: ["all"],
    address: "광주 북구 금남로 200",
    phone: "062-410-XXXX",
    services: ["상담", "교육"],
  },
  {
    id: 610,
    name: "광주 재활요양병원 암재활센터",
    region: "광주",
    type: "rehab",
    cancerTypes: ["all"],
    address: "광주 북구 양일로 309",
    phone: "062-530-XXXX",
    services: ["재활", "물리치료", "통증관리"],
  },
  {
    id: 611,
    name: "한국혈액암협회 광주·전남지부",
    region: "광주",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["상담", "환우지원", "심리지원"],
  },

  // 대전 지역 지원 센터
  {
    id: 701,
    name: "충남대학교병원 암센터",
    region: "대전",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "대전 중구 문화로 282",
    phone: "042-280-7114",
    services: ["치료", "수술", "상담", "정밀의료", "재활"],
  },
  {
    id: 702,
    name: "가톨릭대학교 대전성모병원 암센터",
    region: "대전",
    type: "tertiary_hospital",
    cancerTypes: ["all", "breast", "lung", "colon"],
    address: "대전 중구 대흥로 64",
    phone: "042-220-9114",
    services: ["치료", "수술", "상담", "재활"],
  },
  {
    id: 703,
    name: "을지대학교병원 암센터",
    region: "대전",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "대전 서구 둔산서로 95",
    phone: "042-611-3000",
    services: ["치료", "수술", "정밀의료", "상담"],
  },
  {
    id: 704,
    name: "건양대학교병원 암센터",
    region: "대전",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "대전 서구 관저동로 158",
    phone: "042-600-9114",
    services: ["치료", "수술", "재활", "상담"],
  },
  {
    id: 705,
    name: "대전보훈병원 암진료센터",
    region: "대전",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "대전 유성구 자운로 90",
    phone: "042-939-0114",
    services: ["치료", "검진", "상담", "완화의료"],
  },
  {
    id: 706,
    name: "대전의료원 암진료과",
    region: "대전",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["치료", "검진", "상담"],
  },
  {
    id: 707,
    name: "대전광역시 암생존자통합지원센터",
    region: "대전",
    type: "regional",
    cancerTypes: ["all"],
    address: "대전 서구 둔산로 100",
    phone: "042-360-4475",
    services: ["심리지원", "운동 프로그램", "영양교육", "상담", "가족지원"],
  },
  {
    id: 708,
    name: "대전 유성구 암통합지원센터",
    region: "대전",
    type: "psychological",
    cancerTypes: ["all"],
    address: "대전 유성구 대학로 211",
    phone: "042-611-XXXX",
    services: ["상담", "심리지원", "지역 연계"],
  },
  {
    id: 709,
    name: "대전 동구 암환자지원센터",
    region: "대전",
    type: "counseling",
    cancerTypes: ["all"],
    address: "대전 동구 동대전로 159",
    phone: "042-251-XXXX",
    services: ["상담", "교육", "가족지원"],
  },
  {
    id: 710,
    name: "대전 재활전문병원 암 재활클리닉",
    region: "대전",
    type: "rehab",
    cancerTypes: ["all"],
    address: "대전 유성구 복용북로 39",
    phone: "042-863-XXXX",
    services: ["재활", "물리치료", "통증관리", "심리지원"],
  },
  {
    id: 711,
    name: "한국혈액암협회 대전·충청지부",
    region: "대전",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["상담", "환우지원", "심리지원"],
  },

  // 울산 지역 지원 센터
  {
    id: 801,
    name: "울산대학교병원 암센터",
    region: "울산",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "울산 동구 대학병원로 15",
    phone: "052-250-7000",
    services: ["치료", "수술", "상담", "정밀의료", "재활"],
  },
  {
    id: 802,
    name: "동강병원 암센터",
    region: "울산",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "울산 중구 태화로 239",
    phone: "052-241-1114",
    services: ["치료", "수술", "암 검진", "재활"],
  },
  {
    id: 803,
    name: "울산병원 암센터",
    region: "울산",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "울산 남구 월평로 171",
    phone: "052-259-5000",
    services: ["치료", "상담", "재활"],
  },
  {
    id: 804,
    name: "울산시티병원 암진료센터",
    region: "울산",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "울산 중구 꽃대나리로 24",
    phone: "052-219-8500",
    services: ["검진", "치료", "상담"],
  },
  {
    id: 805,
    name: "울산광역시 암생존자통합지원센터",
    region: "울산",
    type: "regional",
    cancerTypes: ["all"],
    address: "울산 남구 돋질로 233",
    phone: "052-256-9642",
    services: ["심리지원", "운동 프로그램", "상담", "가족지원"],
  },
  {
    id: 806,
    name: "울산 남구 암통합지원센터",
    region: "울산",
    type: "psychological",
    cancerTypes: ["all"],
    address: "울산 남구 삼산중로 132",
    phone: "052-226-XXXX",
    services: ["심리지원", "교육", "상담"],
  },
  {
    id: 807,
    name: "울산 북구 암환자지원센터",
    region: "울산",
    type: "counseling",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["상담", "가족지원", "지역지원"],
  },
  {
    id: 808,
    name: "울산 호스피스·완화의료센터",
    region: "울산",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["완화의료", "호스피스", "가족지원"],
  },
  {
    id: 809,
    name: "한국혈액암협회 울산지부",
    region: "울산",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["상담", "환우지원", "교육"],
  },

  // 세종 지역 지원 센터
  {
    id: 901,
    name: "세종충남대학교병원 암센터",
    region: "세종",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "세종특별자치시 보듬3로 20",
    phone: "044-995-4700",
    services: ["치료", "수술", "상담", "재활"],
  },
  {
    id: 902,
    name: "세종시 보건소 암환자 맞춤케어",
    region: "세종",
    type: "counseling",
    cancerTypes: ["all"],
    address: "세종특별자치시 한누리대로 2130",
    phone: "044-868-XXXX",
    services: ["상담", "교육", "검진 연계"],
  },
  {
    id: 903,
    name: "세종시 암통합지원센터",
    region: "세종",
    type: "psychological",
    cancerTypes: ["all"],
    address: "세종특별자치시 노을3로 20",
    phone: "044-864-XXXX",
    services: ["심리지원", "운동 프로그램", "가족지원"],
  },
  {
    id: 904,
    name: "세종시 호스피스·완화의료 지원팀",
    region: "세종",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["완화의료", "호스피스", "가족지원"],
  },
  {
    id: 905,
    name: "한국혈액암협회 세종/충청권 지원팀",
    region: "세종",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["상담", "환우지원", "심리지원"],
  },

  // 강원 지역 지원 센터
  {
    id: 1001,
    name: "강원대학교병원 암센터",
    region: "강원",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "강원 춘천시 백령로 156",
    phone: "033-258-2000",
    services: ["치료", "수술", "상담", "정밀의료", "암 검진"],
  },
  {
    id: 1002,
    name: "연세대학교 원주세브란스기독병원 암센터",
    region: "강원",
    type: "tertiary_hospital",
    cancerTypes: ["all", "breast", "lung", "stomach"],
    address: "강원 원주시 일산로 20",
    phone: "033-741-0114",
    services: ["치료", "수술", "상담", "임상시험", "재활"],
  },
  {
    id: 1003,
    name: "강릉아산병원 암센터",
    region: "강원",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "강원 강릉시 사천면 방동길 38",
    phone: "033-610-3114",
    services: ["치료", "수술", "상담", "암 검진"],
  },
  {
    id: 1004,
    name: "속초의료원 암진료센터",
    region: "강원",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "강원 속초시 영랑해안길 24",
    phone: "033-630-6000",
    services: ["치료", "검진", "상담"],
  },
  {
    id: 1005,
    name: "삼척의료원 암환자 케어센터",
    region: "강원",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "강원 삼척시 오십천로 418",
    phone: "033-570-7000",
    services: ["검진", "상담", "치료"],
  },
  {
    id: 1006,
    name: "강원도 암생존자통합지원센터(춘천)",
    region: "강원",
    type: "regional",
    cancerTypes: ["all"],
    address: "강원 춘천시 효자동 70",
    phone: "033-255-XXXX",
    services: ["심리지원", "운동 프로그램", "가족지원", "상담"],
  },
  {
    id: 1007,
    name: "원주시 암통합지원센터",
    region: "강원",
    type: "psychological",
    cancerTypes: ["all"],
    address: "강원 원주시 시청로 24",
    phone: "033-737-XXXX",
    services: ["심리지원", "상담", "지역 암환자 지원"],
  },
  {
    id: 1008,
    name: "강릉시 암환자지원센터",
    region: "강원",
    type: "counseling",
    cancerTypes: ["all"],
    address: "강원 강릉시 강릉대로 33",
    phone: "033-660-XXXX",
    services: ["상담", "교육", "가족지원"],
  },
  {
    id: 1009,
    name: "한국혈액암협회 강원지부",
    region: "강원",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["환우지원", "심리지원", "교육"],
  },
  {
    id: 1010,
    name: "강원 호스피스·완화의료센터",
    region: "강원",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["완화의료", "호스피스", "가족지원"],
  },

  // 충북 지역 지원 센터
  {
    id: 1101,
    name: "충북대학교병원 암센터",
    region: "충북",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "충북 청주시 서원구 1순환로 776",
    phone: "043-269-6114",
    services: ["치료", "수술", "암 검진", "상담", "정밀의료"],
  },
  {
    id: 1102,
    name: "청주성모병원 암센터",
    region: "충북",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "충북 청주시 흥덕구 서부로 173",
    phone: "043-210-5114",
    services: ["치료", "상담", "수술", "재활"],
  },
  {
    id: 1103,
    name: "건국대학교 충주병원 암센터",
    region: "충북",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "충북 충주시 충원대로 268",
    phone: "043-840-8200",
    services: ["치료", "상담", "재활"],
  },
  {
    id: 1104,
    name: "충주의료원 암진료센터",
    region: "충북",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "충북 충주시 안림로 239",
    phone: "043-871-0114",
    services: ["치료", "검진", "상담"],
  },
  {
    id: 1105,
    name: "제천서울병원 암진료과",
    region: "충북",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "충북 제천시 세명로 327",
    phone: "043-640-8800",
    services: ["치료", "검진", "상담"],
  },
  {
    id: 1106,
    name: "충북지역암센터(충북대학교병원)",
    region: "충북",
    type: "regional",
    cancerTypes: ["all"],
    address: "충북 청주시 서원구 1순환로 776",
    phone: "043-269-6363",
    services: ["심리지원", "가족지원", "운동 프로그램", "영양 교육"],
  },
  {
    id: 1107,
    name: "청주시 암통합지원센터",
    region: "충북",
    type: "psychological",
    cancerTypes: ["all"],
    address: "충북 청주시 상당구 상당로 69",
    phone: "043-201-XXXX",
    services: ["심리지원", "상담", "가족지원"],
  },
  {
    id: 1108,
    name: "충주시 암환자지원센터",
    region: "충북",
    type: "counseling",
    cancerTypes: ["all"],
    address: "충북 충주시 예성로 36",
    phone: "043-850-XXXX",
    services: ["상담", "교육", "지역 암환자 지원"],
  },
  {
    id: 1109,
    name: "보은군 암환자 통합지원실",
    region: "충북",
    type: "counseling",
    cancerTypes: ["all"],
    address: "충북 보은군 보은읍 차정길 50",
    phone: "043-540-XXXX",
    services: ["상담", "보건소 기반 지원", "교육"],
  },
  {
    id: 1110,
    name: "한국혈액암협회 충북지부",
    region: "충북",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["환우지원", "심리지원", "교육"],
  },
  {
    id: 1111,
    name: "충북 호스피스·완화의료센터",
    region: "충북",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["완화의료", "호스피스", "가족지원", "심리지원"],
  },
  {
    id: 1502,
    name: "청주한국병원 암클리닉",
    region: "충북",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "충북 청주시 흥덕구 2순환로 1230",
    phone: "043-719-7000",
    services: ["치료", "수술", "상담"],
  },
  {
    id: 1503,
    name: "충북 오송 베스티안병원 암재활센터",
    region: "충북",
    type: "rehab",
    cancerTypes: ["all"],
    address: "충북 청주시 흥덕구 오송읍 오송생명로 191",
    phone: "043-910-9000",
    services: ["재활", "통증관리", "완화의료", "심리지원"],
  },
  {
    id: 1504,
    name: "충청북도 청주시 보건소 암환자 지원실",
    region: "충북",
    type: "counseling",
    cancerTypes: ["all"],
    address: "충북 청주시 상당구 상당로 155",
    phone: "043-201-2000",
    services: ["상담", "교육", "가족지원"],
  },
  {
    id: 1505,
    name: "충청북도 암생존자통합지지센터",
    region: "충북",
    type: "regional",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["심리지원", "운동 프로그램", "영양상담", "가족지원"],
  },
  {
    id: 1507,
    name: "제천시 보건소 암환자 지원실",
    region: "충북",
    type: "counseling",
    cancerTypes: ["all"],
    address: "충북 제천시 의림대로 242",
    phone: "043-650-XXXX",
    services: ["상담", "교육", "지역 지원"],
  },
  {
    id: 1508,
    name: "옥천군 보건소 암환자 상담실",
    region: "충북",
    type: "counseling",
    cancerTypes: ["all"],
    address: "충북 옥천군 옥천읍 중앙로 99",
    phone: "043-730-XXXX",
    services: ["상담", "가족지원"],
  },

  // 충남 지역 지원 센터
  {
    id: 1201,
    name: "단국대학교병원 암센터",
    region: "충남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "충남 천안시 동남구 망향로 201",
    phone: "041-550-7114",
    services: ["치료", "수술", "정밀의료", "상담", "재활"],
  },
  {
    id: 1202,
    name: "순천향대학교천안병원 암센터",
    region: "충남",
    type: "tertiary_hospital",
    cancerTypes: ["all", "breast", "lung", "stomach"],
    address: "충남 천안시 동남구 순천향6길 31",
    phone: "041-570-2114",
    services: ["치료", "수술", "재활", "상담"],
  },
  {
    id: 1203,
    name: "건양대학교병원 천안암센터",
    region: "충남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "충남 천안시 서북구 흥얼길 25",
    phone: "041-567-XXXX",
    services: ["치료", "상담", "검진"],
  },
  {
    id: 1204,
    name: "홍성의료원 암진료센터",
    region: "충남",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "충남 홍성군 홍성읍 조양로 224",
    phone: "041-630-6114",
    services: ["치료", "상담", "검진"],
  },
  {
    id: 1205,
    name: "서산의료원 암진료과",
    region: "충남",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "충남 서산시 안견로 200",
    phone: "041-689-XXXX",
    services: ["치료", "상담"],
  },
  {
    id: 1206,
    name: "아산충무병원 암센터",
    region: "충남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "충남 아산시 시민로 388",
    phone: "041-529-XXXX",
    services: ["치료", "수술", "상담"],
  },
  {
    id: 1207,
    name: "천안시 암통합지원센터",
    region: "충남",
    type: "regional",
    cancerTypes: ["all"],
    address: "충남 천안시 서북구 불당동 163-1",
    phone: "041-521-XXXX",
    services: ["심리지원", "운동 프로그램", "영양교육", "가족지원"],
  },
  {
    id: 1208,
    name: "아산시 암환자 통합지원센터",
    region: "충남",
    type: "psychological",
    cancerTypes: ["all"],
    address: "충남 아산시 온천대로 790",
    phone: "041-540-XXXX",
    services: ["심리지원", "상담", "가족지원"],
  },
  {
    id: 1209,
    name: "논산시 암환자지원센터",
    region: "충남",
    type: "counseling",
    cancerTypes: ["all"],
    address: "충남 논산시 시민로 210",
    phone: "041-746-XXXX",
    services: ["상담", "교육"],
  },
  {
    id: 1210,
    name: "보령시 암센터 상담실",
    region: "충남",
    type: "counseling",
    cancerTypes: ["all"],
    address: "충남 보령시 성주산로 77",
    phone: "041-930-XXXX",
    services: ["상담", "교육", "맞춤 지원"],
  },
  {
    id: 1211,
    name: "충남서부 호스피스·완화의료센터",
    region: "충남",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["완화의료", "호스피스", "가족지원"],
  },
  {
    id: 1212,
    name: "한국혈액암협회 충남지부",
    region: "충남",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["상담", "환우지원", "교육"],
  },
  {
    id: 1603,
    name: "충청남도의료원 천안병원 암진료센터",
    region: "충남",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "충남 천안시 동남구 충절로 71",
    phone: "041-570-7200",
    services: ["진단", "완화의료", "상담"],
  },
  {
    id: 1608,
    name: "천안시 보건소 암환자지원실",
    region: "충남",
    type: "counseling",
    cancerTypes: ["all"],
    address: "충남 천안시 서북구 번영로 156",
    phone: "041-521-2661",
    services: ["상담", "교육", "검진 연계"],
  },
  {
    id: 1609,
    name: "아산시 보건소 암환자지원센터",
    region: "충남",
    type: "counseling",
    cancerTypes: ["all"],
    address: "충남 아산시 남부로 370",
    phone: "041-537-3300",
    services: ["상담", "가족지원"],
  },
  {
    id: 1611,
    name: "서천군 보건소 암환자상담센터",
    region: "충남",
    type: "counseling",
    cancerTypes: ["all"],
    address: "충남 서천군 서천읍 군청로 57",
    phone: "041-950-XXXX",
    services: ["상담", "건강관리", "검진 연계"],
  },
  {
    id: 1612,
    name: "논산시 보건소 암환자 가족지원센터",
    region: "충남",
    type: "psychological",
    cancerTypes: ["all"],
    address: "충남 논산시 시민로 243",
    phone: "041-746-XXXX",
    services: ["가족지원", "상담", "심리지원"],
  },

  // 전라북도 지역 지원 센터
  {
    id: 1301,
    name: "전북대학교병원 암센터",
    region: "전북",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "전북 전주시 덕진구 건지로 20",
    phone: "063-250-1114",
    services: ["치료", "수술", "정밀의료", "상담", "암 검진"],
  },
  {
    id: 1302,
    name: "원광대학교병원 암센터",
    region: "전북",
    type: "tertiary_hospital",
    cancerTypes: ["all", "stomach", "breast", "lung"],
    address: "전북 익산시 무왕로 895",
    phone: "063-859-1114",
    services: ["치료", "수술", "완화의료", "상담"],
  },
  {
    id: 1303,
    name: "군산의료원 암진료과",
    region: "전북",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "전북 군산시 의료원로 27",
    phone: "063-472-5000",
    services: ["진단", "치료", "상담"],
  },
  {
    id: 1304,
    name: "익상의료원 암진료센터",
    region: "전북",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "전북 익산시 무왕로 234",
    phone: "063-859-XXXX",
    services: ["진단", "치료", "상담"],
  },
  {
    id: 1305,
    name: "전라북도 권역암생존자통합지지센터",
    region: "전북",
    type: "regional",
    cancerTypes: ["all"],
    address: "전북 전주시 완산구 백제로 45",
    phone: "063-222-XXXX",
    services: ["심리지원", "운동 프로그램", "영양교육", "가족지원"],
  },
  {
    id: 1306,
    name: "전주시 암통합지원센터",
    region: "전북",
    type: "psychological",
    cancerTypes: ["all"],
    address: "전북 전주시 덕진구 기린대로 444",
    phone: "063-222-XXXX",
    services: ["심리지원", "상담", "가족지원"],
  },
  {
    id: 1307,
    name: "익산시 암환자지원센터",
    region: "전북",
    type: "counseling",
    cancerTypes: ["all"],
    address: "전북 익산시 인북로 231",
    phone: "063-859-XXXX",
    services: ["상담", "교육", "지원 프로그램"],
  },
  {
    id: 1308,
    name: "군산시 암통합지원센터",
    region: "전북",
    type: "psychological",
    cancerTypes: ["all"],
    address: "전북 군산시 공단대로 221",
    phone: "063-454-XXXX",
    services: ["심리지원", "상담", "가족지원"],
  },
  {
    id: 1309,
    name: "정읍아산병원 암센터",
    region: "전북",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "전북 정읍시 충정로 606",
    phone: "063-530-6000",
    services: ["치료", "상담", "재활"],
  },
  {
    id: 1310,
    name: "한국혈액암협회 전북지부",
    region: "전북",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["상담", "환우지원", "교육"],
  },

  // 전라남도 지역 지원 센터
  {
    id: 1401,
    name: "전남대학교병원 암센터",
    region: "전남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "광주 동구 제봉로 42",
    phone: "062-220-5114",
    services: ["치료", "수술", "정밀의료", "암 검진", "상담"],
  },
  {
    id: 1402,
    name: "화순전남대학교병원(전남대병원 암특화)",
    region: "전남",
    type: "tertiary_hospital",
    cancerTypes: ["all", "lung", "colon", "breast", "thyroid"],
    address: "전남 화순군 화순읍 서양로 322",
    phone: "061-379-7114",
    services: ["치료", "수술", "방사선치료", "면역항암치료", "임상연구"],
  },
  {
    id: 1403,
    name: "순천의료원 암진료과",
    region: "전남",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "전남 순천시 조례2길 16",
    phone: "061-759-9200",
    services: ["진단", "검진", "상담"],
  },
  {
    id: 1404,
    name: "목포한국병원 암센터",
    region: "전남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "전남 목포시 영산로 483",
    phone: "061-280-3000",
    services: ["수술", "치료", "상담"],
  },
  {
    id: 1405,
    name: "목포기독병원 암센터",
    region: "전남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "전남 목포시 백년대로 303",
    phone: "061-280-7500",
    services: ["치료", "상담", "재활"],
  },
  {
    id: 1406,
    name: "전라남도 암생존자통합지지센터",
    region: "전남",
    type: "regional",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["심리지원", "운동 프로그램", "영양교육", "가족지원"],
  },
  {
    id: 1407,
    name: "목포시 암통합지원센터",
    region: "전남",
    type: "psychological",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["상담", "심리지원", "가족지원"],
  },
  {
    id: 1408,
    name: "여수시 암환자지원센터",
    region: "전남",
    type: "counseling",
    cancerTypes: ["all"],
    address: "전남 여수시 시청로 1",
    phone: "061-659-XXXX",
    services: ["상담", "교육", "지역 지원"],
  },
  {
    id: 1409,
    name: "순천시 정신건강복지센터(암환자 심리지원)",
    region: "전남",
    type: "psychological",
    cancerTypes: ["all"],
    address: "전남 순천시 중앙로 232",
    phone: "061-749-6575",
    services: ["심리지원", "상담"],
  },
  {
    id: 1410,
    name: "완화의료·호스피스센터(전남 화순군)",
    region: "전남",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["완화의료", "호스피스", "가족지원"],
  },
  {
    id: 1411,
    name: "한국혈액암협회 전남지부",
    region: "전남",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["상담", "환우지원", "교육"],
  },

  // 경상북도 지역 지원 센터
  {
    id: 1701,
    name: "경북대학교병원 칠곡캠퍼스 암센터",
    region: "경북",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "대구 북구 호국로 807",
    phone: "053-200-2114",
    services: ["치료", "수술", "정밀의료", "상담", "재활"],
  },
  {
    id: 1702,
    name: "안동병원 암센터",
    region: "경북",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "경북 안동시 앙실로 11",
    phone: "054-840-1114",
    services: ["치료", "검진", "수술", "상담"],
  },
  {
    id: 1703,
    name: "포항세명기독병원 암센터",
    region: "경북",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "경북 포항시 남구 포스코대로 351",
    phone: "054-275-0005",
    services: ["치료", "수술", "상담", "재활"],
  },
  {
    id: 1704,
    name: "동국대학교 경주병원 암센터",
    region: "경북",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "경북 경주시 동대로 87",
    phone: "054-748-9300",
    services: ["치료", "검진", "수술", "상담"],
  },
  {
    id: 1705,
    name: "포항성모병원 암센터",
    region: "경북",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "경북 포항시 대잠동길 17",
    phone: "054-260-8000",
    services: ["치료", "검진", "완화의료", "상담"],
  },
  {
    id: 1706,
    name: "김천제일병원 암진료과",
    region: "경북",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "경북 김천시 신음동3길 56",
    phone: "054-420-9300",
    services: ["진단", "치료", "상담"],
  },
  {
    id: 1707,
    name: "영주적십자병원 암센터",
    region: "경북",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "경북 영주시 번영로 52",
    phone: "054-630-0100",
    services: ["진단", "치료", "상담"],
  },
  {
    id: 1708,
    name: "경북도립 안동의료원 암진료과",
    region: "경북",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "경북 안동시 태화중앙로 99",
    phone: "054-850-6000",
    services: ["치료", "검진", "상담"],
  },
  {
    id: 1709,
    name: "경주시 보건소 암환자 지원실",
    region: "경북",
    type: "counseling",
    cancerTypes: ["all"],
    address: "경북 경주시 양정로 260",
    phone: "054-779-8573",
    services: ["상담", "교육", "지역지원"],
  },
  {
    id: 1710,
    name: "포항시 북구 보건소 암환자 지원센터",
    region: "경북",
    type: "counseling",
    cancerTypes: ["all"],
    address: "경북 포항시 북구 삼호로 369",
    phone: "054-270-4141",
    services: ["상담", "가족지원", "교육"],
  },
  {
    id: 1711,
    name: "구미시 암통합지원센터",
    region: "경북",
    type: "regional",
    cancerTypes: ["all"],
    address: "경북 구미시 송동로 55",
    phone: "054-480-5600",
    services: ["운동 프로그램", "심리지원", "상담"],
  },
  {
    id: 1712,
    name: "경북 암생존자 통합지원센터",
    region: "경북",
    type: "regional",
    cancerTypes: ["all"],
    address: "경북 안동시 북문로 139",
    phone: "054-840-XXXX",
    services: ["심리지원", "교육", "가족지원", "상담"],
  },
  {
    id: 1713,
    name: "문경시 보건소 암환자 상담실",
    region: "경북",
    type: "psychological",
    cancerTypes: ["all"],
    address: "경북 문경시 당교3길 25",
    phone: "054-550-8230",
    services: ["심리지원", "상담"],
  },
  {
    id: 1714,
    name: "한국혈액암협회 경북지부",
    region: "경북",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["환우지원", "상담", "심리지원"],
  },

  // 경상남도 지역 지원 센터
  {
    id: 1801,
    name: "창원경상국립대학교병원 암센터",
    region: "경남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "창원시 성산구 삼정자로 11",
    phone: "055-214-2114",
    services: ["치료", "수술", "검진", "재활", "상담"],
  },
  {
    id: 1802,
    name: "양산부산대학교병원 암센터",
    region: "경남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "양산시 물금읍 금오로 20",
    phone: "055-360-1114",
    services: ["치료", "정밀의료", "수술", "상담"],
  },
  {
    id: 1803,
    name: "창원파티마병원 암센터",
    region: "경남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "창원시 의창구 창이대로 45",
    phone: "055-270-1000",
    services: ["치료", "수술", "상담", "검진"],
  },
  {
    id: 1804,
    name: "창원한마음병원 암센터",
    region: "경남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "창원시 성산구 반지로 15",
    phone: "055-225-9000",
    services: ["치료", "검진", "수술", "상담"],
  },
  {
    id: 1805,
    name: "세종병원 암진료센터(경남)",
    region: "경남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "창원시 마산회원구 팔용로 158",
    phone: "055-240-3000",
    services: ["치료", "검진", "상담"],
  },
  {
    id: 1806,
    name: "진주경상대학교병원 암센터",
    region: "경남",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "진주시 강남로 79",
    phone: "055-750-8000",
    services: ["치료", "수술", "정밀의료", "상담", "재활"],
  },
  {
    id: 1807,
    name: "통영적십자병원 암진료과",
    region: "경남",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "통영시 중앙로 97",
    phone: "055-644-8901",
    services: ["치료", "검진", "상담"],
  },
  {
    id: 1808,
    name: "사천시 보건소 암환자 지원실",
    region: "경남",
    type: "counseling",
    cancerTypes: ["all"],
    address: "사천시 용현면 시청로 77",
    phone: "055-831-3623",
    services: ["상담", "교육", "가족지원"],
  },
  {
    id: 1809,
    name: "거제시 보건소 암환자 상담실",
    region: "경남",
    type: "counseling",
    cancerTypes: ["all"],
    address: "거제시 계룡로 125",
    phone: "055-639-6114",
    services: ["상담", "교육", "지역 지원"],
  },
  {
    id: 1810,
    name: "양산시 암환자 통합지원센터",
    region: "경남",
    type: "psychological",
    cancerTypes: ["all"],
    address: "양산시 양산대로 849",
    phone: "055-392-5075",
    services: ["심리지원", "운동 프로그램", "가족지원"],
  },
  {
    id: 1811,
    name: "창원시 암생존자 통합지원센터",
    region: "경남",
    type: "regional",
    cancerTypes: ["all"],
    address: "창원시 마산합포구 3·15대로 144",
    phone: "055-225-XXXX",
    services: ["심리지원", "운동 프로그램", "영양교육", "상담"],
  },
  {
    id: 1812,
    name: "진주시 암생존자 통합지원센터",
    region: "경남",
    type: "regional",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["심리지원", "운동 프로그램", "영양교육", "상담"],
  },
  {
    id: 1813,
    name: "거창군 보건소 암환자 상담실",
    region: "경남",
    type: "counseling",
    cancerTypes: ["all"],
    address: "거창군 거창읍 중앙로 103",
    phone: "055-940-8327",
    services: ["상담", "지역지원"],
  },
  {
    id: 1814,
    name: "김해시 암환자 통합지원센터",
    region: "경남",
    type: "psychological",
    cancerTypes: ["all"],
    address: "김해시 김해대로 2401",
    phone: "055-330-XXXX",
    services: ["심리지원", "상담", "가족지원"],
  },
  {
    id: 1815,
    name: "한국혈액암협회 경남지부",
    region: "경남",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["환우지원", "교육", "상담"],
  },

  // 제주도 지역 지원 센터
  {
    id: 1901,
    name: "제주대학교병원 암센터",
    region: "제주",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "제주시 아란13길 15",
    phone: "064-717-1114",
    services: ["치료", "검진", "수술", "상담"],
  },
  {
    id: 1902,
    name: "제주한라병원 암센터",
    region: "제주",
    type: "tertiary_hospital",
    cancerTypes: ["all"],
    address: "제주시 연덕로 20",
    phone: "064-740-5000",
    services: ["치료", "검진", "수술", "재활"],
  },
  {
    id: 1903,
    name: "서귀포의료원 암진료과",
    region: "제주",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "서귀포시 장수로 47",
    phone: "064-730-3000",
    services: ["치료", "검진", "상담"],
  },
  {
    id: 1904,
    name: "제주암생존자통합지원센터",
    region: "제주",
    type: "regional",
    cancerTypes: ["all"],
    address: "제주시 서광로 56",
    phone: "064-766-2777",
    services: ["심리지원", "운동 프로그램", "영양교육", "상담"],
  },
  {
    id: 1905,
    name: "제주시 보건소 암환자 상담실",
    region: "제주",
    type: "counseling",
    cancerTypes: ["all"],
    address: "제주시 중앙로 210",
    phone: "064-728-4141",
    services: ["상담", "교육", "가족지원"],
  },
  {
    id: 1906,
    name: "서귀포시 보건소 암환자 상담실",
    region: "제주",
    type: "counseling",
    cancerTypes: ["all"],
    address: "서귀포시 중앙로 101",
    phone: "064-760-6000",
    services: ["상담", "교육", "가족지원"],
  },
  {
    id: 1907,
    name: "제주 온 누리 심리지원센터",
    region: "제주",
    type: "psychological",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["심리지원", "상담", "가족지원"],
  },
  {
    id: 1908,
    name: "한국혈액암협회 제주지부",
    region: "제주",
    type: "nonprofit",
    cancerTypes: ["leukemia", "lymphoma"],
    address: "검색 필요",
    phone: "1661-2701",
    services: ["환우지원", "상담", "교육"],
  },

  // 울릉도 지역 지원 센터
  {
    id: 1909,
    name: "울릉군의료원",
    region: "울릉도",
    type: "public_rehab",
    cancerTypes: ["all"],
    address: "울릉군 울릉읍 울릉로 320",
    phone: "054-790-2500",
    services: ["기본 진료", "검진", "상담"],
  },
  {
    id: 1910,
    name: "울릉군 보건의료원 상담실",
    region: "울릉도",
    type: "counseling",
    cancerTypes: ["all"],
    address: "울릉군 울릉읍 울릉순환로 396",
    phone: "054-123-4567",
    services: ["상담", "보건교육", "기초지원"],
  },
  {
    id: 1911,
    name: "울릉군 방문보건센터 암환자 지원팀",
    region: "울릉도",
    type: "psychological",
    cancerTypes: ["all"],
    address: "검색 필요",
    phone: "xxx-xxxx-xxxx",
    services: ["가정방문", "심리지원", "기초관리"],
  },

  // 독도 지역 정보
  {
    id: 1912,
    name: "독도는 상주 의료기관 없음",
    region: "독도",
    type: "none",
    cancerTypes: [],
    address: "독도에는 의료기관이 없어 울릉군의료원 이용 필요",
    phone: "없음",
    services: ["정보 제공"],
  },
];

export default supportCenters;
